### ISSUE TITLE
how to run minio as daemon on macOS?

### ISSUE THREAD

**Issue by gondo** [minio/minio-service#12]
i've installed minio via brew but can't use brew services to run it as it doesn't allow me to specify custom port. the config gets overwritten each time by brew running script.
I need to specify custom port as port 9000 is used for php-fpm and i can't change that.
in terms of priority php-fpm>minio

**Comment by harshavardhana** [comment]
We don't use macOS systems, feel free to send a PR by fixing this issue @gondo

**Comment by kannappanr** [comment]
Closing this issue as stale.
