### ISSUE TITLE
Proposal for a better systemd service file on Linux

### ISSUE THREAD

**Issue by OlliC** [minio/minio-service#13]
Hi, 

i have just started using minio on Linux (for restic backups) and have some suggestions and questions regarding the systemd service file. 

The first thing is there are some options in there with their default values. This include StandardOutput, StandardError, SuccessExitStatus and KillSignal. Also Group if its the same as User. These can simply be omitted. 

The second thing would be the use of /etc/default. This is a relict from the old days of SysV init. Its a better idea to put these values directly into the service file. They can be edited there as easily as in /etc/default and everything is in one place and less error prone. This is considered best practice by the systemd developers also, see [1]. 

The third thing is rather a question than a suggestion, but why should minio only be restarted on clean exit codes? Is minio really that crash resistant that it never crashes? Even if it would be there are other ways it could be killed for example by the kernels oom killer. I think it should be restarted in those cases. 

I guess disabling the stop timeout logic has something to do with letting minio write data to disk when getting stopped, so i let this as it this.

So this is the cleaned up service file i suggest for minio and which i am currently using:

```
[Unit]
Description=Minio
Documentation=https://docs.minio.io
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
WorkingDirectory=/usr/local/
User=minio-user

ExecStart=/usr/local/bin/minio server --config-dir /etc/minio /zmain/minio-data

Restart=always

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=infinity
SendSIGKILL=no

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

[1] http://0pointer.de/blog/projects/on-etc-sysinit.html

**Comment by harshavardhana** [comment]
Thanks for the pointers @OlliC - feel free to send a PR.

**Comment by OlliC** [comment]
No problem. I didn't had the time to put a PR together. Thanks for creating one.

**Comment by harshavardhana** [comment]
Closing this issue as fixed thanks @OlliC
