### ISSUE TITLE
Linux minio.service systemd file environment variable test logic is reversed

### ISSUE THREAD

**Issue by thatfrankwayne** [minio/minio-service#15]
The minio.service file contains a reference to an EnvironmentFile followed by a check to see if the required environment values are set (see below). (The number of checks varies between stand-alone and distributed scripts.) All the tests use the -n operator, which checks if the string is non-zero-length. If the variable is non-zero-length (like it should be), the code generates a warning. It should be the other way around and use a -z, not an -n.

`ExecStartPre=/bin/bash -c "[ -n \"${MINIO_VOLUMES}\" ] && echo \"Variable MINIO_VOLUMES not set in /etc/default/minio\""`

BTW, the service still runs. It just generates confusing errors every time it is started.

**Comment by kannappanr** [comment]
@thatfrankwayne Thanks for filing this issue. Do you mind sending a PR to fix this issue?

**Comment by thatfrankwayne** [comment]
I created a PR for each file.
