### ISSUE TITLE
Where to find the access key and secret?

### ISSUE THREAD

**Issue by chriscchau** [minio/minio-service#21]
I deployed the systemd service. It can be started with no problem. However I don't know where to find the auto-generated access key and secret. I use "-C /etc/minio --address :9000" as the startup argument. 

Thanks

**Comment by harshavardhana** [comment]
minio doesn't display keys in systemd like envs, because of security requirements. You have to set one yourself using MINIO_ACCESS_KEY, MINIO_SECRET_KEY.
