### ISSUE TITLE
Got issue with IE11

### ISSUE THREAD

**Issue by littlewey** [minio/minio-service#5]
**minio-server version:** latest
**browser** : IE 11
**issue**: stopped before showing Keys
**fault code in F12**:

```
SCRIPT438: Object doesn't support property or method 'assign'
File: index_bundle-2017-02-15T22-41-23Z.js, Line: 30, Column: 27472
```

**simular fault:** https://github.com/mozilla-services/react-jsonschema-form/issues/206

Could you please help with this issue?

**detailed version:**
```
Version: 2017-02-16T01:47:30Z
Release-Tag: RELEASE.2017-02-16T01-47-30Z
Commit-ID: 3d98311d9f4ceb78dba996dcdc0751253241e697
```

**Comment by harshavardhana** [comment]
@littlewey can you open bug on Minio server project ?

Thanks will close the issue here.

**Comment by littlewey** [comment]
Thanks @harshavardhana , sorry for putting things wrongly here.

**Comment by littlewey** [comment]
bug raised here: https://github.com/minio/minio/issues/3898
