### ISSUE TITLE
Minio windows service doc has incorrect screenshots

### ISSUE THREAD

**Issue by nitisht** [minio/minio-service#7]
Windows service doc here: https://github.com/minio/minio-service/blob/master/windows/README.md can be improved by -

- Updating the screenshot.
- Adding steps on how to start services in windows.

**Comment by harshavardhana** [comment]
Should we fix this? @nitisht

**Comment by nitisht** [comment]
yes, will do it @harshavardhana

**Comment by harshavardhana** [comment]
this is fixed by f89d802623ee1eaa99d95b8148ae3d7819ac0293
