### ISSUE TITLE
Service fails to start on Ubuntu 16.04

### ISSUE THREAD

**Issue by nodesocket** [minio/minio-service#9]
Is the following line https://github.com/minio/minio-service/blob/master/linux-systemd/minio.service#L16 correct? Notice the `-` before the path `/etc/default/minio`.

I keep on getting `Variable MINIO_VOLUMES not set in /etc/default/minio` when trying to start the service even though I confirmed that I have a `/etc/default/minio` file and `MINIO_VOLUMES` is set.

**Comment by harshavardhana** [comment]
Yes it is correct @nodesocket we deploy using this script all the time.

**Comment by nodesocket** [comment]
And the format inside of `/etc/default/minio` is just:

```
MINIO_VOLUMES="/mnt/disks/minio_data"
```

**Comment by harshavardhana** [comment]
Here is how i have 

```
cat /etc/default/minio 
# Local export path.
MINIO_VOLUMES="/tmp/minio/"
# Use if you want to run Minio on a custom port.
MINIO_OPTS="--address :9199"
```

```
 sudo systemctl status minio.service
● minio.service - Minio
   Loaded: loaded (/etc/systemd/system/minio.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-09-19 01:04:51 PDT; 3s ago
     Docs: https://docs.minio.io
  Process: 22508 ExecStartPre=/bin/bash -c [ -n "${MINIO_VOLUMES}" ] || echo "Variable MINIO_VOLUMES not set in /etc/defaults/minio" (code=exited, status=0/SUCCESS)
 Main PID: 22512 (minio)
    Tasks: 9
   Memory: 5.0M
      CPU: 94ms
   CGroup: /system.slice/minio.service
           └─22512 /usr/local/bin/minio server --address :9199 /tmp/minio/

Sep 19 01:04:51 prtsc minio[22512]:    http://10.0.0.13:9199  http://172.23.0.1:9199  http://172.17.0.1:9199  http://172.18.0.1:9199  http://172.19.0.1:9199  http://172.20.0
Sep 19 01:04:51 prtsc minio[22512]: Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
Sep 19 01:04:51 prtsc minio[22512]:    $ mc config host add myminio http://10.0.0.13:9199 USWUXHGYZQYFYFFIT3RE MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03
Sep 19 01:04:51 prtsc minio[22512]: Object API (Amazon S3 compatible):
Sep 19 01:04:51 prtsc minio[22512]:    Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
Sep 19 01:04:51 prtsc minio[22512]:    Java:       https://docs.minio.io/docs/java-client-quickstart-guide
Sep 19 01:04:51 prtsc minio[22512]:    Python:     https://docs.minio.io/docs/python-client-quickstart-guide
Sep 19 01:04:51 prtsc minio[22512]:    JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
Sep 19 01:04:51 prtsc minio[22512]:    .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
Sep 19 01:04:51 prtsc minio[22512]: Drive Capacity: 25 GiB Free, 55 GiB Total
```

Are you sure your  `User` and `Group` entries are correct?

**Comment by nodesocket** [comment]
@harshavardhana how are you creating the minio user? Specifically what flags?

Here is what I am using which is not working:

     sudo adduser --system --no-create-home --shell /bin/false --group --disabled-login minio

**Comment by nodesocket** [comment]
@harshavardhana found my problem. Because I was creating the user with `--no-create-home` minio failed to write configuration directories.

     Sep 20 03:02:36 minio1 minio[1853]: time="2017-09-20T03:02:36Z" level=fatal msg="Unable to create configuration directories." cause="mkdir /home/minio: permission denied"

Is there a way to specify a different directory to use as the configuration directory?

**Comment by harshavardhana** [comment]
Yes you can @nodesocket you can add `--config-dir`

**Comment by harshavardhana** [comment]
@nodesocket closing this bug as answered.. feel free to re-open if you have more questions and issues.
